#!/usr/bin/env python3
"""Verify and typeset all 108 annual-inference stress-test cells."""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path

import pandas as pd


PROJECT = Path(__file__).resolve().parent.parent
SOURCE = PROJECT / "output_corrected" / "year_inference_simulation_summary.csv"
OUTPUT = PROJECT / "output_extension_methods"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def table_header(caption: str, label: str, columns: str,
                 headings: str) -> list[str]:
    return [
        "% Requires \\usepackage{longtable,pdflscape} and \\usepackage{booktabs}.",
        "\\begin{landscape}",
        "\\tiny",
        "\\setlength{\\tabcolsep}{2.2pt}",
        f"\\begin{{longtable}}{{{columns}}}",
        f"\\caption{{{caption}}}\\label{{{label}}}\\\\",
        "\\toprule",
        headings + " \\\\",
        "\\midrule",
        "\\endfirsthead",
        f"\\multicolumn{{{len(columns)}}}{{c}}{{\\tablename\\ \\thetable\\ (continued)}} \\\\",
        "\\toprule",
        headings + " \\\\",
        "\\midrule",
        "\\endhead",
        "\\midrule",
        f"\\multicolumn{{{len(columns)}}}{{r}}{{Continued on next page}} \\\\",
        "\\endfoot",
        "\\bottomrule",
        "\\endlastfoot",
    ]


def effect_label(value: str) -> str:
    return {"null": "Null", "moderate": "$-3.5\\%$",
            "application": "$-7\\%$"}[value]


def innovation_label(value: str) -> str:
    return {"gaussian": "Gaussian", "skewed": "Skewed",
            "t3": "$t_3$"}[value]


def make_results_tables(data: pd.DataFrame) -> tuple[Path, Path]:
    estimation_path = OUTPUT / "extension_year_stress_estimation_longtable.tex"
    rejection_path = OUTPUT / "extension_year_stress_rejection_longtable.tex"

    headings_a = ("$R$ & $\\rho$ & Innovation & Effect & $\\delta$ & Sims. & "
                  "Bias & RMSE & Lag & Cov. S & Cov. NW2 & Cov. HAC & "
                  "$\\bar z$ & SD$(z)$ & $z_{.025}$ & $z_{.975}$")
    lines_a = table_header(
        "Complete annual-sequence stress results: estimation, interval "
        "coverage and standardized-estimator diagnostics. S denotes the "
        "ordinary Student interval; NW2 uses Bartlett lag 2; HAC uses the "
        "growing lag shown in the table.",
        "tab:year-stress-estimation", "rrllrrrrrrrrrrrr", headings_a,
    )
    for row in data.itertuples(index=False):
        lines_a.append(
            f"{row.sample_size} & {row.rho:.1f} & "
            f"{innovation_label(row.innovation)} & {effect_label(row.effect)} & "
            f"{row.true_effect:.3f} & {row.simulations} & {row.bias:.4f} & "
            f"{row.rmse:.4f} & {row.growing_lag} & "
            f"{row.coverage_student:.3f} & {row.coverage_nw2:.3f} & "
            f"{row.coverage_hac:.3f} & {row.z_mean:.3f} & {row.z_sd:.3f} & "
            f"{row.z_q025:.3f} & {row.z_q975:.3f} \\\\"
        )
    lines_a += ["\\end{longtable}", "\\end{landscape}", ""]
    estimation_path.write_text("\n".join(lines_a), encoding="utf-8")

    headings_b = ("$R$ & $\\rho$ & Innovation & Effect & Student & NW2 & "
                  "HAC & Sign & Three-way (.025)")
    lines_b = table_header(
        "Complete annual-sequence stress results: lower-tail rejection "
        "rates. Null rows estimate size; non-null rows estimate power. The "
        "three-way rule requires Student, NW2 and sign $p$-values all to be "
        "at most 0.025.",
        "tab:year-stress-rejection", "rrllrrrrr", headings_b,
    )
    for row in data.itertuples(index=False):
        lines_b.append(
            f"{row.sample_size} & {row.rho:.1f} & "
            f"{innovation_label(row.innovation)} & {effect_label(row.effect)} & "
            f"{row.rejection_student:.3f} & {row.rejection_nw2:.3f} & "
            f"{row.rejection_hac:.3f} & {row.rejection_sign:.3f} & "
            f"{row.rejection_three_025:.3f} \\\\"
        )
    lines_b += ["\\end{longtable}", "\\end{landscape}", ""]
    rejection_path.write_text("\n".join(lines_b), encoding="utf-8")
    return estimation_path, rejection_path


def make_specification() -> Path:
    path = OUTPUT / "extension_year_stress_specification.tex"
    text = r"""% Generated by code/46_year_stress_complete_table.py
\subsection{Complete specification of the annual-sequence stress experiment}

The experiment crosses four summer counts
$R\in\{20,33,60,120\}$, three autoregressive coefficients
$\rho\in\{0,0.3,0.6\}$, three innovation laws and three effects
$\delta\in\{0,-0.035,-0.07\}$.  The resulting $4\times3\times3\times3=108$
cells each contain 10,000 simulations.  A 200-step burn-in precedes every
retained sequence.  For simulation $s$,
\[
 U_r=\rho U_{r-1}+(1-\rho^2)^{1/2}\varepsilon_r,
 \qquad Y_r=\delta+0.12U_r .
\]
The Gaussian innovation is standard normal.  The skewed innovation is
\[
 \frac{\exp(0.65Z)-\exp(0.65^2/2)}
 {\{[\exp(0.65^2)-1]\exp(0.65^2)\}^{1/2}},\qquad Z\sim N(0,1),
\]
and the heavy-tailed innovation is $T_3/\sqrt{3}$.  Thus every innovation has
mean zero and unit variance (where defined by the stated law), and 0.12 is the
marginal standard-deviation scale before serial dependence is introduced.

The point estimate is $\bar Y$.  The ordinary Student interval uses the sample
variance and a $t_{R-1}$ critical value.  NW2 uses the lag-2 Bartlett long-run
variance with the same critical value.  The growing-lag HAC interval uses
$L=\max\{1,\lfloor R^{1/3}\rfloor\}$ and a standard-normal critical value.
The three lower-tail tests use their corresponding standard errors; the sign
test uses the exact binomial upper tail of the number of negative summers.
The reported three-way decision requires the Student, NW2 and sign $p$-values
all to be at most 0.025.  Standardized diagnostics use the population
long-run variance $0.12^2(1+\rho)/(1-\rho)$.

Tables~\ref{tab:year-stress-estimation} and
\ref{tab:year-stress-rejection} report all 108 cells without filtering.
"""
    path.write_text(text, encoding="utf-8")
    return path


def main() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    data = pd.read_csv(SOURCE, keep_default_na=False)
    expected_columns = [
        "sample_size", "rho", "innovation", "effect", "true_effect",
        "simulations", "bias", "rmse", "growing_lag", "coverage_student",
        "coverage_nw2", "coverage_hac", "rejection_student",
        "rejection_nw2", "rejection_hac", "rejection_sign",
        "rejection_three_025", "z_mean", "z_sd", "z_q025", "z_q975",
    ]
    if data.columns.tolist() != expected_columns:
        raise RuntimeError("Annual stress CSV columns differ from frozen output")
    if len(data) != 108 or data.duplicated(
        ["sample_size", "rho", "innovation", "effect"]).any():
        raise RuntimeError("Annual stress output is not 108 unique cells")
    levels = {
        "sample_size": {20, 33, 60, 120},
        "rho": {0.0, 0.3, 0.6},
        "innovation": {"gaussian", "skewed", "t3"},
        "effect": {"null", "moderate", "application"},
    }
    for column, expected in levels.items():
        if set(data[column]) != expected:
            raise RuntimeError(f"Unexpected {column} levels: {set(data[column])}")
    if not data.simulations.eq(10_000).all():
        raise RuntimeError("Not every annual stress cell has 10,000 simulations")

    complete_csv = OUTPUT / "extension_year_stress_108_cells.csv"
    shutil.copyfile(SOURCE, complete_csv)
    if sha256(complete_csv) != sha256(SOURCE):
        raise RuntimeError("Exact CSV-copy verification failed")
    estimation, rejection = make_results_tables(data)
    specification = make_specification()

    outputs = [complete_csv, estimation, rejection, specification]
    audit = {
        "protocol": "EXTENSION_ANALYSIS_PROTOCOL.md",
        "script": str(Path(__file__).resolve().relative_to(PROJECT)),
        "analysis_role": "existing annual stress-test reporting",
        "source": {"path": str(SOURCE.relative_to(PROJECT)),
                   "bytes": SOURCE.stat().st_size, "sha256": sha256(SOURCE)},
        "verification": {
            "rows": len(data), "unique_cells": 108,
            "simulations_per_cell": 10_000,
            "factorial_design": "4 sample sizes x 3 rho x 3 innovations x 3 effects",
            "all_source_columns_typeset_across_two_longtables": True,
            "exact_csv_copy": True,
        },
        "outputs": [{"path": str(path.relative_to(PROJECT)),
                     "bytes": path.stat().st_size, "sha256": sha256(path)}
                    for path in outputs],
    }
    audit_path = OUTPUT / "extension_year_stress_audit.json"
    audit_path.write_text(json.dumps(audit, indent=2), encoding="utf-8")
    print("Verified 108 unique annual stress cells; 10,000 simulations each.")
    print(f"Source/copy SHA-256: {sha256(SOURCE)}")
    print(f"Estimation table rows: {sum(1 for line in estimation.read_text().splitlines() if line.endswith(r'\\'))}")
    print(f"Rejection table rows: {sum(1 for line in rejection.read_text().splitlines() if line.endswith(r'\\'))}")


if __name__ == "__main__":
    main()
